services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3002:3000
    volumes:
      - /opt/homepage:/app/config # Make sure your local config directory exists
      - /opt/homepage/images:/app/public/images
#      - /media/drive2:/media/drive2
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: nlab.casa # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    restart: always