---
- name: Suppress Login Message (hushlogin)
  file:
    path: "/home/{{ item }}/.hushlogin"
    mode: 0644
    owner: "{{ item }}"
    group: "{{ item }}"
    modification_time: preserve
    access_time: preserve
    state: touch
  loop:
    - "{{ username }}"